### ISSUE TITLE
hooker-test does not work on CentOS 7

### ISSUE THREAD

**Issue by CaledoniaProject** [Menooker/PFishHook#8]
```
main=0x400abe
test_replace=0x40084a
test_replace2=0x4008fd
==============================
testfunc
==============================
Before Hook:

Program received signal SIGSEGV, Segmentation fault.
0x0000000000401dbc in ZydisInputPeek ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-307.el7.1.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64
(gdb) bt
#0  0x0000000000401dbc in ZydisInputPeek ()
#1  0x0000000000408995 in ZydisCollectOptionalPrefixes ()
#2  0x000000000040bb40 in ZydisDecoderDecodeBuffer ()
#3  0x00000000004009cb in main::{lambda(void (*)(), int)#1}::operator()(void (*)(), int) const ()
#4  0x0000000000400a35 in main::{lambda(char const*, void (*)(), void (**)(), void (*)())#2}::operator()(char const*, void (*)(), void (**)(), void (*)()) const ()
#5  0x0000000000400b6b in main ()
```

**Comment by Menooker** [comment]
thanks for the issue. I will invesitigate it!
